spring.application.name=f1
openf1.base-url=https://api.openf1.org/v1

spring.devtools.livereload.enabled=true

spring.datasource.url=${F1_APP_DB_URL:jdbc:postgresql://127.0.0.1:5432/f1app}
spring.datasource.username=appuser
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

resilience4j.retry.instances.openF1Retry.max-attempts=5
resilience4j.retry.instances.openF1Retry.wait-duration=2s
resilience4j.retry.instances.openF1Retry.enable-exponential-backoff=true
resilience4j.retry.instances.openF1Retry.exponential-backoff-multiplier=2
resilience4j.retry.instances.openF1Retry.exponential-max-wait-duration=30s
resilience4j.retry.instances.openF1Retry.randomized-wait-factor=0.3

resilience4j.retry.instances.openF1Retry.retry-exceptions[0]=org.springframework.web.reactive.function.client.WebClientResponseException
resilience4j.retry.instances.openF1Retry.retry-exceptions[1]=java.io.IOException
resilience4j.retry.instances.openF1Retry.ignore-exceptions[0]=io.github.resilience4j.ratelimiter.RequestNotPermitted
resilience4j.retry.instances.openF1Retry.ignore-exceptions[1]=io.github.resilience4j.circuitbreaker.CallNotPermittedException

resilience4j.ratelimiter.instances.openF1RateLimiter.limit-for-period=1
resilience4j.ratelimiter.instances.openF1RateLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.openF1RateLimiter.timeout-duration=15s

resilience4j.circuitbreaker.instances.openF1CircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.openF1CircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.openF1CircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.openF1CircuitBreaker.ignore-exceptions[0]=io.github.resilience4j.ratelimiter.RequestNotPermitted

spring.cache.type=caffeine

cors-port=5173

outlier_threshold=1.10