-- Baseline schema, generated from the existing f1app database.
--   pg_dump -h 127.0.0.1 -U appuser -d f1app --schema-only --no-owner --no-privileges --no-comments
-- psql meta-commands (restrict / unrestrict) stripped: Flyway executes plain SQL over JDBC.
-- Existing databases are stamped at this version via baseline-on-migrate and skip it.

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: car_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE car_data (
    id bigint NOT NULL,
    brake boolean,
    date timestamp(6) with time zone,
    driver_number integer,
    drs integer,
    gear integer,
    speed integer,
    throttle integer,
    session_id bigint NOT NULL,
    lap_number integer
);


--
-- Name: car_data_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE car_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME car_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: driver_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE driver_entries (
    id bigint NOT NULL,
    acronym character varying(3),
    driver_number integer,
    season bigint,
    driver_id bigint,
    team_id bigint NOT NULL
);


--
-- Name: driver_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE driver_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME driver_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: driver_standings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE driver_standings (
    id bigint NOT NULL,
    current_points double precision,
    current_position integer,
    meeting_key integer,
    session_key integer,
    start_points double precision,
    start_position integer,
    driver_number integer NOT NULL
);


--
-- Name: driver_standings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE driver_standings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME driver_standings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: driver_team; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE driver_team (
    id bigint NOT NULL,
    team_color character varying(255),
    year integer,
    driver_id bigint NOT NULL,
    team_id bigint NOT NULL
);


--
-- Name: driver_team_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE driver_team ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME driver_team_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: drivers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE drivers (
    id bigint NOT NULL,
    broadcast_name character varying(50),
    country_code character varying(3),
    first_name character varying(50),
    full_name character varying(100),
    headshot_url character varying(512),
    last_name character varying(50),
    normalized_name character varying(100)
);


--
-- Name: drivers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE drivers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME drivers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lap; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE lap (
    id bigint NOT NULL,
    is_pit_lap boolean NOT NULL,
    lap_number integer,
    session_id bigint NOT NULL,
    driver_number integer NOT NULL,
    duration double precision,
    lap_start timestamp(6) with time zone,
    outlier boolean DEFAULT false
);


--
-- Name: lap_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE lap ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lap_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE locations (
    id integer NOT NULL,
    date timestamp(6) with time zone,
    driver_number integer NOT NULL,
    x integer,
    y integer,
    session_id bigint
);


--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meetings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE meetings (
    id bigint NOT NULL,
    circuit_key bigint,
    circuit_name character varying(255),
    country_code character varying(255),
    country_name character varying(255),
    date_start timestamp(6) with time zone,
    location character varying(255),
    meeting_key bigint NOT NULL,
    name character varying(255),
    official_name character varying(255),
    year integer NOT NULL,
    date_end timestamp(6) with time zone
);


--
-- Name: meetings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE meetings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME meetings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: position; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "position" (
    id bigint NOT NULL,
    lap_number integer NOT NULL,
    "position" integer NOT NULL,
    session_id bigint NOT NULL
);


--
-- Name: position_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "position" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME position_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: race_control_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE race_control_event (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    date timestamp(6) with time zone NOT NULL,
    driver_number integer,
    flag character varying(255),
    lap_number integer,
    message character varying(255),
    qualifying_phase character varying(255),
    scope character varying(255),
    sector integer,
    session_id bigint NOT NULL
);


--
-- Name: race_control_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE race_control_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME race_control_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: race_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE race_session (
    id bigint NOT NULL,
    date_end timestamp(6) with time zone NOT NULL,
    date_start timestamp(6) with time zone NOT NULL,
    session_key bigint NOT NULL,
    session_name character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    meeting_id bigint NOT NULL,
    CONSTRAINT race_session_type_check CHECK (((type)::text = ANY ((ARRAY['Practice'::character varying, 'Qualifying'::character varying, 'Race'::character varying])::text[])))
);


--
-- Name: race_session_drivers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE race_session_drivers (
    session_id bigint NOT NULL,
    drivers_id bigint NOT NULL
);


--
-- Name: race_session_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE race_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME race_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE results (
    id bigint NOT NULL,
    dnf boolean,
    dns boolean,
    driver_number integer,
    dsq boolean,
    duration double precision[],
    gap_to_leader character varying(255)[],
    laps double precision,
    meeting_key integer,
    "position" integer,
    session_key integer,
    session_id bigint NOT NULL
);


--
-- Name: results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sector; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE sector (
    id bigint NOT NULL,
    sector integer NOT NULL,
    "time" double precision,
    lap_id bigint NOT NULL,
    segments integer[]
);


--
-- Name: sector_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE sector ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sector_time; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE sector_time (
    id bigint NOT NULL,
    sector integer NOT NULL,
    "time" double precision,
    lap_id integer NOT NULL
);


--
-- Name: sector_time_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE sector_time ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sector_time_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_drivers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE session_drivers (
    session_id bigint NOT NULL,
    driver_id bigint NOT NULL
);


--
-- Name: stints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE stints (
    id bigint NOT NULL,
    compound character varying(255),
    driver_number integer,
    lap_end integer,
    lap_start integer,
    stint_number integer,
    tyre_age_at_start integer,
    meeting_id bigint,
    session_id bigint,
    CONSTRAINT stints_compound_check CHECK (((compound)::text = ANY ((ARRAY['SOFT'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying, 'INTERMEDIATE'::character varying, 'WET'::character varying])::text[])))
);


--
-- Name: stints_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE stints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME stints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE team (
    id bigint NOT NULL,
    name character varying(255),
    team_color character varying(255)
);


--
-- Name: team_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE team ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME team_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_standings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE team_standings (
    id bigint NOT NULL,
    current_points double precision,
    current_position integer,
    meeting_key integer,
    session_key integer,
    start_points double precision,
    start_position integer,
    team_name character varying(255) NOT NULL
);


--
-- Name: team_standings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE team_standings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME team_standings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: car_data car_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY car_data
    ADD CONSTRAINT car_data_pkey PRIMARY KEY (id);


--
-- Name: driver_entries driver_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY driver_entries
    ADD CONSTRAINT driver_entries_pkey PRIMARY KEY (id);


--
-- Name: driver_standings driver_standings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY driver_standings
    ADD CONSTRAINT driver_standings_pkey PRIMARY KEY (id);


--
-- Name: driver_team driver_team_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY driver_team
    ADD CONSTRAINT driver_team_pkey PRIMARY KEY (id);


--
-- Name: drivers drivers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY drivers
    ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);


--
-- Name: lap lap_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY lap
    ADD CONSTRAINT lap_pkey PRIMARY KEY (id);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: meetings meetings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY meetings
    ADD CONSTRAINT meetings_pkey PRIMARY KEY (id);


--
-- Name: position position_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "position"
    ADD CONSTRAINT position_pkey PRIMARY KEY (id);


--
-- Name: race_control_event race_control_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY race_control_event
    ADD CONSTRAINT race_control_event_pkey PRIMARY KEY (id);


--
-- Name: race_session race_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY race_session
    ADD CONSTRAINT race_session_pkey PRIMARY KEY (id);


--
-- Name: results results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY results
    ADD CONSTRAINT results_pkey PRIMARY KEY (id);


--
-- Name: sector sector_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY sector
    ADD CONSTRAINT sector_pkey PRIMARY KEY (id);


--
-- Name: sector_time sector_time_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY sector_time
    ADD CONSTRAINT sector_time_pkey PRIMARY KEY (id);


--
-- Name: stints stints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY stints
    ADD CONSTRAINT stints_pkey PRIMARY KEY (id);


--
-- Name: team team_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY team
    ADD CONSTRAINT team_pkey PRIMARY KEY (id);


--
-- Name: team_standings team_standings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY team_standings
    ADD CONSTRAINT team_standings_pkey PRIMARY KEY (id);


--
-- Name: race_session uk1khgsknumlmhu1fcd7a8yqa8d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY race_session
    ADD CONSTRAINT uk1khgsknumlmhu1fcd7a8yqa8d UNIQUE (session_key);


--
-- Name: meetings uk6546j7vjac7oe3aqr0prtscs9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY meetings
    ADD CONSTRAINT uk6546j7vjac7oe3aqr0prtscs9 UNIQUE (meeting_key);


--
-- Name: car_data uk7ocurtc7jqdah91ssyy0fcln4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY car_data
    ADD CONSTRAINT uk7ocurtc7jqdah91ssyy0fcln4 UNIQUE (driver_number, session_id, date);


--
-- Name: results uk_result_session_driver; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY results
    ADD CONSTRAINT uk_result_session_driver UNIQUE (session_id, driver_number);


--
-- Name: drivers uke598el50e7wwbo3cfu5woei95; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY drivers
    ADD CONSTRAINT uke598el50e7wwbo3cfu5woei95 UNIQUE (normalized_name);


--
-- Name: driver_standings ukg0l0gr4mac08r50u3gst3gn6x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY driver_standings
    ADD CONSTRAINT ukg0l0gr4mac08r50u3gst3gn6x UNIQUE (session_key, driver_number);


--
-- Name: locations ukhe6i0eiepyake7sw5f1ig99y; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY locations
    ADD CONSTRAINT ukhe6i0eiepyake7sw5f1ig99y UNIQUE (date, driver_number);


--
-- Name: position uki3vs8ylm7loflyigwq0f3ksax; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "position"
    ADD CONSTRAINT uki3vs8ylm7loflyigwq0f3ksax UNIQUE (session_id, "position");


--
-- Name: lap ukil5kg3645oyo067kn5kyxsh88; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY lap
    ADD CONSTRAINT ukil5kg3645oyo067kn5kyxsh88 UNIQUE (session_id, driver_number, lap_number);


--
-- Name: team_standings ukipso8p3wgn7wwq6omueycp6xv; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY team_standings
    ADD CONSTRAINT ukipso8p3wgn7wwq6omueycp6xv UNIQUE (session_key, team_name);


--
-- Name: race_session_drivers ukkrcewf0r6tgwljsa01k1d894c; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY race_session_drivers
    ADD CONSTRAINT ukkrcewf0r6tgwljsa01k1d894c UNIQUE (drivers_id);


--
-- Name: stints ukkvisphql407q7quriypa83ye7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY stints
    ADD CONSTRAINT ukkvisphql407q7quriypa83ye7 UNIQUE (stint_number, session_id, driver_number);


--
-- Name: sector ukn7a1a38qkndvcly89wvxh473; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY sector
    ADD CONSTRAINT ukn7a1a38qkndvcly89wvxh473 UNIQUE (lap_id, sector);


--
-- Name: sector_time uknnxmahv0duhossaw0he6sexiq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY sector_time
    ADD CONSTRAINT uknnxmahv0duhossaw0he6sexiq UNIQUE (lap_id, sector);


--
-- Name: driver_team ukoss5n957un40abpw3kkpnmr3u; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY driver_team
    ADD CONSTRAINT ukoss5n957un40abpw3kkpnmr3u UNIQUE (driver_id, year);


--
-- Name: race_control_event ukp2l4p13ejtjrxo6yhp3kiq4mf; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY race_control_event
    ADD CONSTRAINT ukp2l4p13ejtjrxo6yhp3kiq4mf UNIQUE (session_id, date, category, driver_number);


--
-- Name: driver_entries uktjnyr8hkfty81xbhrlwpbqkid; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY driver_entries
    ADD CONSTRAINT uktjnyr8hkfty81xbhrlwpbqkid UNIQUE (driver_id, season);


--
-- Name: idx_driver_team_driver; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_driver_team_driver ON driver_team USING btree (driver_id);


--
-- Name: idx_driver_team_team; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_driver_team_team ON driver_team USING btree (team_id);


--
-- Name: idx_driver_team_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_driver_team_year ON driver_team USING btree (year);


--
-- Name: idx_lap_driver_number; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lap_driver_number ON lap USING btree (driver_number);


--
-- Name: idx_lap_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lap_session ON lap USING btree (session_id);


--
-- Name: idx_location_session_driver_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_location_session_driver_date ON locations USING btree (session_id, driver_number, date);


--
-- Name: idx_rce_lap_number; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rce_lap_number ON race_control_event USING btree (lap_number);


--
-- Name: idx_rce_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rce_session ON race_control_event USING btree (session_id);


--
-- Name: idx_result_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_result_session ON results USING btree (session_id);


--
-- Name: idx_session_meeting; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_meeting ON race_session USING btree (meeting_id);


--
-- Name: session_drivers fk2dq4mj4r2yqwuiiavqn60tq4p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY session_drivers
    ADD CONSTRAINT fk2dq4mj4r2yqwuiiavqn60tq4p FOREIGN KEY (session_id) REFERENCES race_session(id);


--
-- Name: results fk4aobtvlirx5pligbhh2748f1t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY results
    ADD CONSTRAINT fk4aobtvlirx5pligbhh2748f1t FOREIGN KEY (session_id) REFERENCES race_session(id);


--
-- Name: stints fk6pw5guf6o6e01ddbnphix0og9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY stints
    ADD CONSTRAINT fk6pw5guf6o6e01ddbnphix0og9 FOREIGN KEY (session_id) REFERENCES race_session(id);


--
-- Name: race_session_drivers fk98c0ivtbk1mn09pbdtr7xj1vd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY race_session_drivers
    ADD CONSTRAINT fk98c0ivtbk1mn09pbdtr7xj1vd FOREIGN KEY (session_id) REFERENCES race_session(id);


--
-- Name: race_session_drivers fkbws51avxaj779l4hmklpgf1ml; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY race_session_drivers
    ADD CONSTRAINT fkbws51avxaj779l4hmklpgf1ml FOREIGN KEY (drivers_id) REFERENCES drivers(id);


--
-- Name: position fkg2eel2gnq6r4iqxtoo1vekgd0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "position"
    ADD CONSTRAINT fkg2eel2gnq6r4iqxtoo1vekgd0 FOREIGN KEY (session_id) REFERENCES race_session(id);


--
-- Name: car_data fkk72pov3o28balkd6p7dg0s1f0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY car_data
    ADD CONSTRAINT fkk72pov3o28balkd6p7dg0s1f0 FOREIGN KEY (session_id) REFERENCES race_session(id);


--
-- Name: locations fkkbact40ukaaqa16kh5rfmfgbm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY locations
    ADD CONSTRAINT fkkbact40ukaaqa16kh5rfmfgbm FOREIGN KEY (session_id) REFERENCES race_session(id);


--
-- Name: driver_team fklmo3f43hdq3oeqqrg1v2gexbf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY driver_team
    ADD CONSTRAINT fklmo3f43hdq3oeqqrg1v2gexbf FOREIGN KEY (team_id) REFERENCES team(id);


--
-- Name: driver_entries fklvmplor269708nrv231xypl66; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY driver_entries
    ADD CONSTRAINT fklvmplor269708nrv231xypl66 FOREIGN KEY (team_id) REFERENCES team(id);


--
-- Name: lap fkmqvk331e8k7u8qdkuo9ardpde; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY lap
    ADD CONSTRAINT fkmqvk331e8k7u8qdkuo9ardpde FOREIGN KEY (session_id) REFERENCES race_session(id);


--
-- Name: stints fknl833h6to1886bg3gexp4x27f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY stints
    ADD CONSTRAINT fknl833h6to1886bg3gexp4x27f FOREIGN KEY (meeting_id) REFERENCES meetings(id);


--
-- Name: driver_team fknrfyr26elm2y97r5w1dd9guti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY driver_team
    ADD CONSTRAINT fknrfyr26elm2y97r5w1dd9guti FOREIGN KEY (driver_id) REFERENCES drivers(id);


--
-- Name: driver_entries fkoorpbiuj0r9wahaubjgvmdocc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY driver_entries
    ADD CONSTRAINT fkoorpbiuj0r9wahaubjgvmdocc FOREIGN KEY (driver_id) REFERENCES drivers(id);


--
-- Name: sector fkowf74si6j3ob3n6sagv7198k6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY sector
    ADD CONSTRAINT fkowf74si6j3ob3n6sagv7198k6 FOREIGN KEY (lap_id) REFERENCES lap(id);


--
-- Name: race_session fkpqim07bpsntk8jlf4b15ne2nq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY race_session
    ADD CONSTRAINT fkpqim07bpsntk8jlf4b15ne2nq FOREIGN KEY (meeting_id) REFERENCES meetings(id);


--
-- Name: sector_time fkq4b66fvij0ppooosp0j5kovs0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY sector_time
    ADD CONSTRAINT fkq4b66fvij0ppooosp0j5kovs0 FOREIGN KEY (lap_id) REFERENCES lap(id);


--
-- Name: session_drivers fkqekebjwrnks1it3p2qbxtq5bq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY session_drivers
    ADD CONSTRAINT fkqekebjwrnks1it3p2qbxtq5bq FOREIGN KEY (driver_id) REFERENCES drivers(id);


--
-- Name: race_control_event fkt5hwmml9tpjwteb6rnc5w7ow2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY race_control_event
    ADD CONSTRAINT fkt5hwmml9tpjwteb6rnc5w7ow2 FOREIGN KEY (session_id) REFERENCES race_session(id);


--
-- PostgreSQL database dump complete
--


